# .render.yaml - SpringMart H2 (file-based)

services:
  - type: web
    name: springmart-backend
    env: java
    plan: free
    build:
      command: ./springmart-backend/springmart/mvnw clean package -DskipTests
      publish: springmart-backend/springmart/target/*.jar
    startCommand: java -jar springmart-backend/springmart/target/springmart-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: PORT
        value: 8080
