# .render.yaml - SpringMart Backend Deployment
# Explicitly configured for Java/Spring Boot monorepo

services:
  - type: web
    name: springmart-backend
    env: java
    plan: free
    region: oregon
    buildCommand: |
      echo "Setting up Java environment..."
      java -version
      echo "Building Spring Boot application..."
      chmod +x ./mvnw
      ./mvnw -f springmart-backend/springmart/pom.xml clean package -DskipTests
    startCommand: java -jar springmart-backend/springmart/target/springmart-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: PORT
        value: 8080
      - key: JAVA_VERSION
        value: 21
      - key: MAVEN_OPTS
        value: "-Xmx512m"
    buildFilter:
      paths:
        - springmart-backend/**
        - mvnw
        - .mvn/**
        - system.properties
        - Procfile
    autoDeploy: true
