# .render.yaml - SpringMart Backend Deployment
# Explicitly configured for Java/Spring Boot monorepo

# Force Java environment using Docker
services:
  - type: web
    name: springmart-backend-java
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: PORT
        value: 8080
    autoDeploy: true
