# .render.yaml - SpringMart Backend Deployment
# Explicitly configured for Java/Spring Boot monorepo

services:
  - type: web
    name: springmart-backend
    env: java
    plan: free
    buildCommand: ./mvnw -f springmart-backend/springmart/pom.xml clean package -DskipTests
    startCommand: java -jar springmart-backend/springmart/target/springmart-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: PORT
        value: 8080
