# .render.yaml - SpringMart H2 (file-based)

services:
  - type: web
    name: springmart-backend
    env: java
    build:
      command: ./mvnw clean package -DskipTests
      publish: target/*.jar
    startCommand: java -jar target/springmart-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
